function config = RCA_Config()
% RCA_Config  Central configuration for the root cause analysis workflow.
%
% All thresholds in this file are heuristics unless the workbook provides
% a direct physical limit. They are kept here so calibration is explicit
% and easy to review.

config = struct();

config.General.Version = "1.0.1";
config.General.DefaultExcelFile = fullfile(fileparts(fileparts(mfilename('fullpath'))), ...
    'info', 'eBus_Model_Info.xlsx');
config.General.DefaultResultsFolder = 'RCA_Results';
config.General.TimestampFormat = 'yyyyMMdd_HHmmss';
config.General.MaxRecursiveDepth = 8;
config.General.DefaultReserveSOC_pct = 10;
config.General.MinimumDistanceForWhpkm_km = 0.05;
config.General.MinimumDynamicSamples = 3;
config.General.TextLineWidth = 110;
config.General.HeuristicNote = "Thresholds are editable heuristics unless explicitly tied to workbook data.";

config.PreferredReferenceSignals = { ...
    'time_sim', 'veh_vel', 'veh_pos', 'batt_pwr', 'veh_acc', 'batt_soc', ...
    'emot1_pwr', 'gr_num', 'acc_pdl'};

config.RequiredSignalNames = { ...
    'time_sim', 'veh_vel', 'veh_pos', 'veh_acc', 'veh_des_vel', ...
    'road_slp', 'acc_pdl', 'brk_pdl', ...
    'batt_curr', 'batt_volt', 'batt_pwr', 'batt_loss_pwr', 'batt_soc', 'batt_temp', ...
    'batt_chrg_curr_lim', 'batt_dischrg_curr_lim', 'batt_chrg_pwr_lim', 'batt_dischrg_pwr_lim', ...
    'emot1_dem_trq', 'emot2_dem_trq', 'emot1_act_trq', 'emot2_act_trq', ...
    'emot1_act_spd', 'emot2_act_spd', 'emot1_pwr', 'emot2_pwr', ...
    'emot1_loss_pwr', 'emot2_loss_pwr', 'emot1_max_av_trq', 'emot2_max_av_trq', ...
    'gr_num', 'gr_ratio', 'gbx_out_trq', 'gbx_out_spd', 'gbx_pwr_loss', ...
    'net_trac_trq', 'fric_brk_force', 'fric_brk_pwr', ...
    'roll_res_force', 'grad_force', 'aero_drag_force', 'whl_force', ...
    'aux_curr', 'aux_volt'};

config.SignalFallback = struct();
config.SignalFallback.PreferredContainers = {'logout', 'out', 'logsout', 'simout', 'ans', 'data', 'sMP'};
config.SignalFallback.PreferredTimeNames = {'time', 'tout', 't', 'Time', 'Tout', 'sec', 'secs'};
config.SignalFallback.MinimumFallbackScore = 4;
config.SignalFallback.AmbiguityMargin = 1;
config.SignalFallback.DiscreteTokenList = {'gear', 'mode', 'state', 'flag', 'switch'};

config.Thresholds.StopSpeed_kmh = 1.0;
config.Thresholds.CreepSpeed_kmh = 5.0;
config.Thresholds.UrbanSpeedUpper_kmh = 40.0;
config.Thresholds.HighwaySpeed_kmh = 60.0;
config.Thresholds.CruiseAccelAbs_mps2 = 0.15;
config.Thresholds.SignificantAccel_mps2 = 0.35;
config.Thresholds.SignificantDecel_mps2 = -0.35;
config.Thresholds.UphillSlope_pct = 1.0;
config.Thresholds.SteepSlope_pct = 3.0;
config.Thresholds.DownhillSlope_pct = -1.0;
config.Thresholds.HighAuxPower_kW = 5.0;
config.Thresholds.HighAuxShare_pct = 15.0;
config.Thresholds.PoorEfficiencyMultiplier = 1.15;
config.Thresholds.PoorTrackingError_kmh = 5.0;
config.Thresholds.SevereTrackingError_kmh = 10.0;
config.Thresholds.MinSegmentDuration_s = 15.0;
config.Thresholds.MinStopDuration_s = 8.0;
config.Thresholds.MaxShortSegmentMergeDuration_s = 10.0;
config.Thresholds.GearHuntingWindow_s = 20.0;
config.Thresholds.GearShiftRate_perkm = 8.0;
config.Thresholds.MinGearDwell_s = 10.0;
config.Thresholds.HighLossShare_pct = 12.0;
config.Thresholds.LowSOC_pct = 20.0;
config.Thresholds.CriticalSOC_pct = 10.0;
config.Thresholds.ColdAmbient_C = 5.0;
config.Thresholds.HotAmbient_C = 35.0;
config.Thresholds.LimitUsageFraction = 0.90;
config.Thresholds.VoltageSag_pct = 5.0;
config.Thresholds.EarlyUpShiftFractionOfMaxSpeed = 0.45;
config.Thresholds.LateUpShiftFractionOfMaxSpeed = 0.85;
config.Thresholds.LowMotorEfficiencySpeedFraction = 0.15;
config.Thresholds.HighMotorEfficiencySpeedFraction = 0.85;
config.Thresholds.LowMotorEfficiencyTorqueFraction = 0.10;
config.Thresholds.RegenOpportunityBrakePower_kW = 10.0;
config.Thresholds.PoorRegenRecoveryFraction = 0.35;
config.Thresholds.WorstSegmentCount = 5;
config.Thresholds.MinEventDuration_s = 2.0;
config.Thresholds.DriverPedalActive_pct = 5.0;
config.Thresholds.DriverPedalOverlap_pct = 5.0;
config.Thresholds.DriverCoastPedal_pct = 1.0;
config.Thresholds.DriverHighAccelPedal_pct = 80.0;
config.Thresholds.DriverHighBrakePedal_pct = 40.0;
config.Thresholds.DriverTrackingBand_kmh = 2.0;
config.Thresholds.DriverShiftInfluenceWindow_s = 2.0;
config.Thresholds.DriverOscillationRate_per_s = 0.15;
config.Thresholds.DriverBadEventSeverity = 1.10;

config.RootCauseWeights = struct();
config.RootCauseWeights.Slope = 1.20;
config.RootCauseWeights.Auxiliary = 1.00;
config.RootCauseWeights.LowSOC = 1.00;
config.RootCauseWeights.BatteryLimit = 1.20;
config.RootCauseWeights.GearOperation = 1.25;
config.RootCauseWeights.RollingResistance = 0.90;
config.RootCauseWeights.AeroDrag = 0.80;
config.RootCauseWeights.ControllerTracking = 1.00;
config.RootCauseWeights.MotorInverter = 1.10;
config.RootCauseWeights.Transmission = 0.95;
config.RootCauseWeights.RegenMiss = 1.00;

config.Plot = struct();
config.Plot.FontSize = 11;
config.Plot.AxisLineWidth = 1.0;
config.Plot.LineWidth = 1.4;
config.Plot.FigurePosition = [100 100 1300 760];
config.Plot.Colors.Vehicle = [0.10 0.35 0.70];
config.Plot.Colors.Demand = [0.90 0.45 0.10];
config.Plot.Colors.Battery = [0.20 0.60 0.30];
config.Plot.Colors.Motor = [0.75 0.20 0.25];
config.Plot.Colors.Gear = [0.55 0.30 0.70];
config.Plot.Colors.Auxiliary = [0.20 0.65 0.65];
config.Plot.Colors.Slope = [0.45 0.30 0.10];
config.Plot.Colors.Warning = [0.85 0.15 0.15];
config.Plot.Colors.Neutral = [0.30 0.30 0.30];

thresholdNames = { ...
    'StopSpeed_kmh', 'CreepSpeed_kmh', 'UrbanSpeedUpper_kmh', 'HighwaySpeed_kmh', 'CruiseAccelAbs_mps2', 'SignificantAccel_mps2', ...
    'SignificantDecel_mps2', 'UphillSlope_pct', 'SteepSlope_pct', 'DownhillSlope_pct', ...
    'HighAuxPower_kW', 'HighAuxShare_pct', 'PoorEfficiencyMultiplier', ...
    'PoorTrackingError_kmh', 'SevereTrackingError_kmh', 'MinSegmentDuration_s', ...
    'MinStopDuration_s', 'GearHuntingWindow_s', 'GearShiftRate_perkm', ...
    'MinGearDwell_s', 'HighLossShare_pct', 'LowSOC_pct', 'CriticalSOC_pct', 'ColdAmbient_C', 'HotAmbient_C', ...
    'LimitUsageFraction', 'VoltageSag_pct', 'EarlyUpShiftFractionOfMaxSpeed', ...
    'LateUpShiftFractionOfMaxSpeed', 'PoorRegenRecoveryFraction', ...
    'DriverPedalActive_pct', 'DriverPedalOverlap_pct', 'DriverCoastPedal_pct', ...
    'DriverHighAccelPedal_pct', 'DriverHighBrakePedal_pct', 'DriverTrackingBand_kmh', ...
    'DriverShiftInfluenceWindow_s', 'DriverOscillationRate_per_s', 'DriverBadEventSeverity'};

thresholdValues = [ ...
    config.Thresholds.StopSpeed_kmh, config.Thresholds.CreepSpeed_kmh, config.Thresholds.UrbanSpeedUpper_kmh, config.Thresholds.HighwaySpeed_kmh, ...
    config.Thresholds.CruiseAccelAbs_mps2, config.Thresholds.SignificantAccel_mps2, ...
    config.Thresholds.SignificantDecel_mps2, config.Thresholds.UphillSlope_pct, ...
    config.Thresholds.SteepSlope_pct, config.Thresholds.DownhillSlope_pct, ...
    config.Thresholds.HighAuxPower_kW, config.Thresholds.HighAuxShare_pct, ...
    config.Thresholds.PoorEfficiencyMultiplier, config.Thresholds.PoorTrackingError_kmh, ...
    config.Thresholds.SevereTrackingError_kmh, config.Thresholds.MinSegmentDuration_s, ...
    config.Thresholds.MinStopDuration_s, config.Thresholds.GearHuntingWindow_s, ...
    config.Thresholds.GearShiftRate_perkm, config.Thresholds.MinGearDwell_s, ...
    config.Thresholds.HighLossShare_pct, config.Thresholds.LowSOC_pct, ...
    config.Thresholds.CriticalSOC_pct, config.Thresholds.ColdAmbient_C, config.Thresholds.HotAmbient_C, config.Thresholds.LimitUsageFraction, ...
    config.Thresholds.VoltageSag_pct, config.Thresholds.EarlyUpShiftFractionOfMaxSpeed, ...
    config.Thresholds.LateUpShiftFractionOfMaxSpeed, config.Thresholds.PoorRegenRecoveryFraction, ...
    config.Thresholds.DriverPedalActive_pct, config.Thresholds.DriverPedalOverlap_pct, config.Thresholds.DriverCoastPedal_pct, ...
    config.Thresholds.DriverHighAccelPedal_pct, config.Thresholds.DriverHighBrakePedal_pct, config.Thresholds.DriverTrackingBand_kmh, ...
    config.Thresholds.DriverShiftInfluenceWindow_s, config.Thresholds.DriverOscillationRate_per_s, config.Thresholds.DriverBadEventSeverity]';

thresholdUnits = { ...
    'km/h', 'km/h', 'km/h', 'km/h', 'm/s^2', 'm/s^2', 'm/s^2', '%', '%', '%', ...
    'kW', '%', '-', 'km/h', 'km/h', 's', 's', 's', ...
    'shifts/km', 's', '%', '%', '%', 'degC', 'degC', '-', '%', '-', '-', '-', ...
    '%', '%', '%', '%', '%', 'km/h', 's', '1/s', '-'};

thresholdRationale = { ...
    'Vehicle considered stopped below this speed to separate halt and rolling states.', ...
    'Below this speed the bus is treated as low-speed creep rather than steady operation.', ...
    'Demand speed below this upper bound is treated as urban operation.', ...
    'Demand speed above this threshold is treated as highway or sustained high-speed operation.', ...
    'Acceleration magnitude below this value is treated as quasi-steady cruise.', ...
    'Positive acceleration above this value is treated as a meaningful propulsion event.', ...
    'Negative acceleration below this value is treated as a meaningful braking/deceleration event.', ...
    'Positive road slope above this value is treated as an uphill segment.', ...
    'Slope above this value is treated as a severe grade load in RCA scoring.', ...
    'Negative road slope below this value is treated as a downhill segment.', ...
    'Average auxiliary power above this value is flagged as materially affecting range.', ...
    'Auxiliary energy share above this value is flagged as a significant burden.', ...
    'Segment efficiency above trip median by this factor is marked poor-efficiency.', ...
    'Mean absolute speed tracking error above this level is flagged as poor tracking.', ...
    'Tracking error above this level is treated as severe underperformance.', ...
    'Shorter segments are merged to avoid noise-driven fragmentation.', ...
    'Stops longer than this value become explicit stop segments.', ...
    'Back-and-forth shifts within this window contribute to gear-hunting detection.', ...
    'Shift density above this value is treated as excessive for an electric bus duty cycle.', ...
    'Gear dwell below this value suggests unstable ratio selection.', ...
    'Loss share above this value is treated as materially high.', ...
    'Average SoC below this value is treated as low SoC operation.', ...
    'Average SoC below this value is treated as critical and performance-risking.', ...
    'Ambient temperature below this value is treated as cold-weather exposure.', ...
    'Ambient temperature above this value is treated as hot-weather exposure.', ...
    'Use of power/current limit above this fraction is treated as active battery limiting.', ...
    'Voltage drop of this fraction from segment entry is treated as sag evidence.', ...
    'Upshifts below this speed fraction are heuristically treated as early.', ...
    'Upshifts above this speed fraction are heuristically treated as late.', ...
    'Recovered braking fraction below this value indicates weak regen utilization.', ...
    'Pedal above this threshold is treated as active driver demand.', ...
    'Simultaneous accelerator and brake above this threshold is flagged as overlap.', ...
    'Both pedals below this threshold are treated as coasting demand.', ...
    'Accelerator above this threshold is treated as a strong propulsion request.', ...
    'Brake above this threshold is treated as a strong braking request.', ...
    'Speed error within this band is treated as acceptable driver tracking.', ...
    'Poor tracking inside this window after a gear change is attributed partly to shift interaction.', ...
    'Cruise error sign reversals above this rate are treated as oscillatory controller behaviour.', ...
    'Driver event severity above this heuristic is treated as a bad event.'};

config.ThresholdTable = table(string(thresholdNames(:)), thresholdValues, string(thresholdUnits(:)), ...
    string(thresholdRationale(:)), 'VariableNames', {'Threshold', 'Value', 'Unit', 'Rationale'});
end
