function signal = RCA_GetSignalData(store, signalName)
% RCA_GetSignalData  Retrieve a signal or specification entry from a store.

signal = struct( ...
    'Available', false, ...
    'Name', string(signalName), ...
    'Description', "", ...
    'Unit', "", ...
    'Subsystem', "", ...
    'Status', "Missing", ...
    'Note', "Signal not available.", ...
    'Data', [], ...
    'Time', [], ...
    'AlignedData', [], ...
    'AlignedTime', [], ...
    'Approximate', false, ...
    'ExpressionUsed', "", ...
    'Confidence', "Low");

if nargin < 1 || isempty(store) || ~isstruct(store)
    return;
end

rawName = char(string(signalName));
candidateFields = unique({rawName, matlab.lang.makeValidName(rawName), ...
    matlab.lang.makeValidName(strrep(rawName, '.', '_'))});

for iField = 1:numel(candidateFields)
    if isfield(store, candidateFields{iField})
        signal = store.(candidateFields{iField});
        return;
    end
end

storeFields = fieldnames(store);
normalizedTarget = regexprep(rawName, '[^a-zA-Z0-9]', '');
for iField = 1:numel(storeFields)
    candidate = regexprep(storeFields{iField}, '[^a-zA-Z0-9]', '');
    if strcmpi(candidate, normalizedTarget)
        signal = store.(storeFields{iField});
        return;
    end
end
end
